### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by daltonmenezes** [ilariaventurini/colors-convert#15]
Hi, I'm not being able to use colors-convert using typescript with ts-node-dev. I'm getting the following error:

```js
yarn dev
yarn run v1.22.10
$ tsnd --respawn --transpile-only --ignore-watch node_modules src/index.ts
[INFO] 22:18:37 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.3.4)
/Users/daltonmenezes/projetos/github/new-aura/node_modules/colors-convert/dist/index.js:1
export { isHex, isRgb, isRgba, isCmyk, isHsl, isHsla, isColor } from './lib/types/isType';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Module._compile (/Users/daltonmenezes/projetos/github/new-aura/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.nodeDevHook [as .js] (/Users/daltonmenezes/projetos/github/new-aura/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
[ERROR] 22:18:37 SyntaxError: Unexpected token 'export'
```

**Comment by ilariaventurini** [comment]
Hi Dalton, I'll take a look. Thank you!

**Comment by ilariaventurini** [comment]
I've never used `ts-node-dev` before. I tested [here](https://codesandbox.io/s/colors-convert-with-ts-and-ts-node-dev-3rhqp?file=/package.json) and everything seems to work well. I used your `ts-node-dev` version (1.1.6) and not the last one. Let me know if there are updates.

**Comment by ilariaventurini** [comment]
Hello! Can I have a reproducible example?

**Comment by daltonmenezes** [comment]
Sure, @ilariaventurini.

https://github.com/daltonmenezes/colors-convert-issue-examples

I made two examples, one using TypeScript and the other using JavaScript vanilla in Node.js with esmodules. You can run both by running `yarn dev`.

**Comment by SavageFRVR** [comment]
Still not working in node.js
